export const languages = [
  { name: 'Afrikaans', value: 'af-ZA'},
  { name: 'አማርኛ', value: 'am-ET'},
  { name: 'Azərbaycanca', value: 'az-AZ'},
  { name: 'বাংলা - বাংলাদেশ', value: 'bn-BD'},
  { name: 'বাংলা - ভারত', value: 'bn-IN'},
  { name: 'Bahasa Indonesia', value: 'id-ID'},
  { name: 'Bahasa Melayu', value: 'ms-MY'},
  { name: 'Català', value: 'ca-ES'},
  { name: 'Čeština', value: 'cs-CZ'},
  { name: 'Dansk', value: 'da-DK'},
  { name: 'Deutsch', value: 'de-DE'},
  { name: 'English - Australia', value: 'en-AU'},
  { name: 'English - Canada', value: 'en-CA'},
  { name: 'English - India', value: 'en-IN'},
  { name: 'English - Kenya', value: 'en-KE'},
  { name: 'English - Tanzania', value: 'en-TZ'},
  { name: 'English - Ghana', value: 'en-GH'},
  { name: 'English - New Zealand', value: 'en-NZ'},
  { name: 'English - Nigeria', value: 'en-NG'},
  { name: 'English - South Africa', value: 'en-ZA'},
  { name: 'English - Philippines', value: 'en-PH'},
  { name: 'English - United Kingdom', value: 'en-GB'},
  { name: 'English - United States', value: 'en-US'},
  { name: 'Español - Argentina', value: 'es-AR'},
  { name: 'Español - Chile', value: 'es-CL'},
  { name: 'Español - Bolivia', value: 'es-BO'},
  { name: 'Español - Colombia', value: 'es-CO'},
  { name: 'Español - Costa Rica', value: 'es-CR'},
  { name: 'Español - Ecuador', value: 'es-EC'},
  { name: 'Español - El Salvador', value: 'es-SV'},
  { name: 'Español - España', value: 'es-ES'},
  { name: 'Español - Estados Unidos', value: 'es-US'},
  { name: 'Español - Guatemala', value: 'es-GT'},
  { name: 'Español - Honduras', value: 'es-HN'},
  { name: 'Español - México', value: 'es-MX'},
  { name: 'Español - Nicaragua', value: 'es-NI'},
  { name: 'Español - Panamá', value: 'es-PA'},
  { name: 'Español - Paraguay', value: 'es-PY'},
  { name: 'Español - Perú', value: 'es-PE'},
  { name: 'Español - Puerto Rico', value: 'es-PR'},
  { name: 'Español - República Dominicana', value: 'es-DO'},
  { name: 'Español - Uruguay', value: 'es-UY'},
  { name: 'Español - Venezuela', value: 'es-VE'},
  { name: 'Euskara', value: 'eu-ES'},
  { name: 'Filipino', value: 'fil-PH'},
  { name: 'Français', value: 'fr-FR'},
  { name: 'Basa Jawa', value: 'jv-ID'},
  { name: 'Galego', value: 'gl-ES'},
  { name: 'ગુજરાતી', value: 'gu-IN'},
  { name: 'Hrvatski', value: 'hr-HR'},
  { name: 'IsiZulu', value: 'zu-ZA'},
  { name: 'Íslenska', value: 'is-IS'},
  { name: 'Italiano - Italia', value: 'it-IT'},
  { name: 'Italiano - Svizzera', value: 'it-CH'},
  { name: 'ಕನ್ನಡ', value: 'kn-IN'},
  { name: 'ភាសាខ្មែរ', value: 'km-KH'},
  { name: 'Latviešu', value: 'lv-LV'},
  { name: 'Lietuvių', value: 'lt-LT'},
  { name: 'മലയാളം', value: 'ml-IN'},
  { name: 'मराठी', value: 'mr-IN'},
  { name: 'Magyar', value: 'hu-HU'},
  { name: 'ລາວ', value: 'lo-LA'},
  { name: 'Nederlands', value: 'nl-NL'},
  { name: 'नेपाली भाषा', value: 'ne-NP'},
  { name: 'Norsk bokmål', value: 'nb-NO'},
  { name: 'Polski', value: 'pl-PL'},
  { name: 'Português - Brasil', value: 'pt-BR'},
  { name: 'Português - Portugal', value: 'pt-PT'},
  { name: 'Română', value: 'ro-RO'},
  { name: 'සිංහල', value: 'si-LK'},
  { name: 'Slovenščina', value: 'sl-SI'},
  { name: 'Basa Sunda', value: 'su-ID'},
  { name: 'Slovenčina', value: 'sk-SK'},
  { name: 'Suomi', value: 'fi-FI'},
  { name: 'Svenska', value: 'sv-SE'},
  { name: 'Kiswahili - Tanzania', value: 'sw-TZ'},
  { name: 'Kiswahili - Kenya', value: 'sw-KE'},
  { name: 'ქართული', value: 'ka-GE'},
  { name: 'Հայերեն', value: 'hy-AM'},
  { name: 'தமிழ் - இந்தியா', value: 'ta-IN'},
  { name: 'தமிழ் - சிங்கப்பூர்', value: 'ta-SG'},
  { name: 'தமிழ் - இலங்கை', value: 'ta-LK'},
  { name: 'தமிழ் - மலேசியா', value: 'ta-MY'},
  { name: 'తెలుగు', value: 'te-IN'},
  { name: 'Tiếng Việt', value: 'vi-VN'},
  { name: 'Türkçe', value: 'tr-TR'},
  { name: 'اُردُو - پاکستان', value: 'ur-PK'},
  { name: 'اُردُو - بھارت', value: 'ur-IN'},
  { name: 'Ελληνικά', value: 'el-GR'},
  { name: 'български', value: 'bg-BG'},
  { name: 'Pусский', value: 'ru-RU'},
  { name: 'Српски', value: 'sr-RS'},
  { name: 'Українська', value: 'uk-UA'},
  { name: '한국어', value: 'ko-KR'},
  { name: '中文 - 普通话 (中国大陆)', value: 'cmn-Hans-CN'},
  { name: '中文 - 普通话 (香港)', value: 'cmn-Hans-HK'},
  { name: '中文 - 中文 (台灣)', value: 'cmn-Hant-TW'},
  { name: '中文 - 粵語 (香港)', value: 'yue-Hant-HK'},
  { name: '日本語', value: 'ja-JP'},
  { name: 'हिन्दी', value: 'hi-IN'},
  { name: 'ภาษาไทย', value: 'th-TH'}
];